name: pgeri91.github.io
markdown: kramdown
theme: minima
repository: pgeri91/pgeri91.github.io
collections:
    - wishlist_items
github: [metadata]
wishlist_categories:
    - id: record
      name: "Lemezek"
      has_bg: true
    - id: videogame
      name: "Videójátékok"
      has_bg: true
    - id: computer
      name: "Számítógép alkatrész-periféria"
      has_bg: true
    - id: interior
      name: "Lakberendezés"
      has_bg: true
    - id: sound-instruments
      name: "Hang(szer)"
      has_bg: true
    - id: electronics
      name: "Hobbi-elektronika"
      has_bg: true
    - id: misc
      name: "Egyéb"
      has_bg: false